name: E2E Testing

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prepare e2e tests
      run: npm run pre-test
    - name: Run e2e tests
      run: npm run test:e2e
    - name: Clean up
      run: ./scripts/5-clean-up.sh
