name: Automated Tests

on:
  schedule:
  - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
    - name: Start Redis
      uses: supercharge/redis-github-action@1.4.0
    - name: Use Node.js 22
      uses: actions/setup-node@v3
      with:
        node-version: 22
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm test
    - run: npm run pre-test
    - run: npm run test:e2e
    - run: ./scripts/5-clean-up.sh
